# mockito를 아직 사용하지 않으면, 끄는 것이 build가 매우 빨라진다!
# @freeze와 @JsonSerializable() 을 사용하는 모든 클래스들의 이름에 .gen을 추가하면 된다!

targets:
  $default:
    builders:
      mockito:mockBuilder:
        enabled: false
      freezed:
        generate_for:
          - lib/**/*.gen.dart
      json_serializable:
        generate_for:
          - lib/**/*.gen.dart